export function reviewUi(demo: boolean) {
  const demoData = demo
    ? JSON.stringify([
        { id: 'demo-001', profileUrl: 'https://instagram.com/cafe_demo', message: 'Hello Café Demo, may I share a website improvement idea?' },
        { id: 'demo-002', profileUrl: 'https://instagram.com/studio_demo', message: 'Hello Studio Demo, I prepared a short, no-obligation suggestion.' },
      ])
    : 'null';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Prospecting review</title><style>
:root{color-scheme:dark;font:15px Inter,system-ui;background:#070909;color:#f4f6f5}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#18352c 0,transparent 35%),#070909}.wrap{max-width:980px;margin:auto;padding:48px 20px}header{display:flex;justify-content:space-between;gap:24px;align-items:end;border-bottom:1px solid #26332f;padding-bottom:24px}h1{font-size:clamp(28px,5vw,52px);margin:8px 0}.eyebrow{color:#67e8b4;letter-spacing:.18em;font-size:11px}button,input{border:1px solid #34463f;background:#101614;color:inherit;border-radius:8px;padding:11px 14px}button{cursor:pointer;background:#67e8b4;color:#06100c;font-weight:700}button.secondary{background:#151d1a;color:#dbe5e1}button.danger{background:#ff6b62;color:#160302}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:26px 0}.toolbar input{min-width:280px;flex:1}.notice,.card{border:1px solid #26332f;background:#0d1210;border-radius:12px;padding:18px}.notice{color:#b8c6c0}.grid{display:grid;gap:14px}.card a{color:#67e8b4}.message{white-space:pre-wrap;color:#d9e2de;line-height:1.6;border-left:2px solid #67e8b4;padding-left:14px}.actions{display:flex;gap:10px;margin-top:16px}.state{margin-left:auto;color:#93a39c}.demo{color:#ffd166}small{color:#81918a}</style></head>
<body><main class="wrap"><header><div><div class="eyebrow">HUMAN-IN-THE-LOOP CONTROL</div><h1>Review queue</h1><p>Inspect every profile and message before any send is authorized.</p></div><div id="mode" class="${demo ? 'demo' : ''}">${demo ? 'SYNTHETIC DEMO' : 'LOCAL OPERATOR'}</div></header>
<div class="notice">${demo ? 'This demonstration uses fictional profiles and never calls Instagram or the worker API.' : 'The API key stays in this browser session. Use Emergency stop to block approvals immediately—no restart required.'}</div>
<div class="toolbar">${demo ? '' : '<input id="key" type="password" placeholder="Local worker API key"><button id="load">Load queue</button><button id="stop" class="danger">Emergency stop</button><button id="resume" class="secondary">Resume operation</button>'}<span id="status" class="state"></span></div><section id="queue" class="grid"></section></main>
<script>const demo=${demoData};const queue=document.querySelector('#queue'),status=document.querySelector('#status');const key=document.querySelector('#key');if(key)key.value=sessionStorage.workerKey||'';const headers=()=>({'Authorization':'Bearer '+key.value,'Content-Type':'application/json'});function render(items){queue.innerHTML=items.length?'':'<div class="card">No messages waiting for approval.</div>';for(const item of items){const card=document.createElement('article');card.className='card';card.innerHTML='<a target="_blank" rel="noreferrer"></a><p class="message"></p><small></small><div class="actions"><button>Approve once</button></div>';card.querySelector('a').textContent=item.profileUrl;card.querySelector('a').href=item.profileUrl;card.querySelector('.message').textContent=item.message;card.querySelector('small').textContent='ID: '+item.id;const approve=card.querySelector('button');if(demo){approve.textContent='Demo only — sending disabled';approve.disabled=true}else approve.onclick=()=>approveOne(item,card);queue.append(card)}}async function call(path,options={}){sessionStorage.workerKey=key.value;const response=await fetch(path,{...options,headers:headers()});const body=await response.json();if(!response.ok)throw new Error(body.status||body.error||'Request failed');return body}async function load(){try{status.textContent='Loading…';const body=await call('/messages/prepared');render(body.messages);status.textContent=body.messages.length+' awaiting review'}catch(error){status.textContent=error.message}}async function approveOne(item,card){if(!confirm('Approve this exact message for '+item.profileUrl+'?'))return;try{await call('/message/approve',{method:'POST',body:JSON.stringify({outreachMessageId:item.id,approvalToken:item.id,approved:true})});card.remove();status.textContent='Approved and processed'}catch(error){status.textContent=error.message}}async function control(active){try{const body=await call('/controls/emergency-stop',{method:'POST',body:JSON.stringify({active})});status.textContent=body.emergencyStop?'Emergency stop active':'Operation resumed'}catch(error){status.textContent=error.message}}if(demo)render(demo);else{document.querySelector('#load').onclick=load;document.querySelector('#stop').onclick=()=>control(true);document.querySelector('#resume').onclick=()=>control(false)}</script></body></html>`;
}
